apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: register-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - image: register-sample:v1
        name: register
        env:
#          - name: KUMULUZEE_BASEURL
#            value: http://NODE-IP:SERVICE-NODEPORT
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: minikube
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
