kumuluzee:
  server:
    http:
      port: 8000
  streaming:
    kafka:
      consumer:
        bootstrap-servers: 172.19.0.1:32784
        group-id: group1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.LongDeserializer